apiVersion: apps/v1
kind: Deployment
metadata:
  name: audible-tracker
spec:
  selector:
    matchLabels:
      app: audible-tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: audible-tracker
    spec:
      containers:
      - image: ghcr.io/ho0ber/audible-tracker/audible-tracker:build-4213638713
        imagePullPolicy: Always
        name: audible-tracker
        ports:
        - containerPort: 9999
        volumeMounts:
          - mountPath: "/tmp"
            name: audible-creds
            readOnly: true
      volumes:
        - name: audible-creds
          secret:
            secretName: audible-creds
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: audible-tracker
spec:
  ports:
  - port: 80
    targetPort: 9999
    protocol: TCP
  selector:
    app: audible-tracker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audible-tracker-ingress
  labels:
    kcert.dev/ingress: "managed"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - audible.hoob.io
    secretName: audible-tracker-kcert-tls
  rules:
  - host: audible.hoob.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: audible-tracker
            port:
              number: 80
